os: linux
sudo: required
language: "minimal"

jobs:
  include:
    - name: "tests"
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - ctest

notifications:
  email: false