#os: linux
#sudo: required
#language: "minimal"
#
#jobs:
#  include:
#    - name: "tests"
#      script:
#        - cd tests
#        - cmake -Dtest=ON ..
#        - make GameTests
#
#notifications:
#  email: false

language: cpp

services:
  - docker

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
#
script:
  - git submodule update --init --recursive
  - sudo apt-get install -y libfreetype6-dev libxrandr-dev libudev-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - mkdir -p .build
  - cd .build
  - cmake .. -DBUILD_TESTS=On
  - cmake --build .
  - files=`find . -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"`
  - filter=-build/c++11,-runtime/references,-whitespace/braces,-whitespace/indent,-whitespace/comments,-build/include_order
  - echo "$files" | xargs cpplint --filter=$filter
  - export CTEST_OUTPUT_ON_FAILURE=true
  - CMAKE_LINKER_OPTS="-DCMAKE_EXE_LINKER='-fuse-ld=gold'"
  - CMAKE_CONFIG_OPTS="-DHUNTER_CONFIGURATION_TYPES=Debug -DCMAKE_BUILD_TYPE=Debug"
  - CMAKE_TOOLCHAIN_OPTS="-DCMAKE_TOOLCHAIN_FILE='`pwd`/tools/polly/sanitize-address-cxx17-pic.cmake'"
  - CMAKE_OPTS="$CMAKE_LINKER_OPTS $CMAKE_CONFIG_OPTS $CMAKE_TOOLCHAIN_OPTS"
  - cmake -H. -B_builds/sanitize-address-cxx17 "$CMAKE_OPTS"
  - cmake --build _builds/sanitize-address-cxx17
  - ./_builds/sanitize-address-cxx17/tests
  - CMAKE_TOOLCHAIN_OPTS="-DCMAKE_TOOLCHAIN_FILE='`pwd`/tools/polly/sanitize-thread-cxx17-pic.cmake'"
  - CMAKE_OPTS="$CMAKE_LINKER_OPTS $CMAKE_CONFIG_OPTS $CMAKE_TOOLCHAIN_OPTS"
  - cmake -H. -B_builds/sanitize-thread-cxx17 "$CMAKE_OPTS"
  - cmake --build _builds/sanitize-thread-cxx17
  - ./_builds/sanitize-thread-cxx17/tests

#  jobs:
#    include:
#      - name: "tests"
#        dist: xenial
#        sudo: true
#        compiler: gcc
#        addons:
#          apt:
#            sources:
#              - ubuntu-toolchain-r-test
#            packages:
#              - gcc-8
#              - g++-8
#              - cmake
#        script:
#          - git submodule update --init --recursive
#          - sudo apt-get install -y libfreetype6-dev libxrandr-dev libudev-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev
#          - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
#          - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
#          - mkdir -p .build
#          - cd .build
#          - cmake .. -DBUILD_TESTS=On
#          - cmake --build .
#      - name: "checks"
#        script:
#          - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh